config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  get 'top' => 'searches#top'
  get 'about' => 'users#about'
  post '/users/guest_sign_in', to: 'users#new_guest'

  resources :users, :only => [:show, :edit, :update, :destroy, :index]
  resources :posts, :only => [:new, :create, :show, :destroy, :edit, :update] do
  	resources :post_comments, :only => [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post


end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
    attachment :dish_image

    validates :menu_title, :shop_name, :adress, :comment, length: { minimum: 1 }
    validates :dish_image, :price, presence: true


end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :post
	belongs_to :user

	 validates :comment, length: { minimum: 1 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :user_image

  def already_liked?(post)
    self.favorites.exists?(post_id: post.id)
  end

  enum prefecture: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
  enum genres:{
  	醤油ラーメン:1,塩らーめん:2,味噌ラーメン:3,白湯ラーメン:4,豚骨ラーメン:5,
  	坦々麺:6,ちゃんぽん麺:7,冷麺:8,油そば:9,家系ラーメン:10,二郎系ラーメン:11,
  	つけ麺:12,その他:13
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

    private
	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :prefecture, :genres])
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
  	post = Post.find(params[:post_id])
  	favorite = current_user.favorites.new(post_id: params[:post_id])
  	favorite.save
  	redirect_back(fallback_location: root_path)
  end

  def destroy
  	post = Post.find(params[:post_id])
  	favorite = current_user.favorites.find_by(post_id: post.id)
  	favorite.destroy
  	redirect_back(fallback_location: root_path)
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
before_action :authenticate_user!

  def create
  	post = Post.find(params[:post_id])
  	comment = current_user.post_comments.new(post_comment_params)
  	comment.post_id = post.id

  	if comment.save
  		redirect_to post_path(post)
  	else
  		redirect_to post_path(post) , alert: 'エラーが発生しました'
    end

  end

  def destroy
  	PostComment.find_by(id: params[:id], post_id: params[:post_id]).destroy
  	redirect_to post_path(params[:post_id])
  end

  private
  def post_comment_params
  	params.require(:post_comment).permit(:comment)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:edit, :new, :update, :destroy, :create]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		post =Post.find(params[:id])
		post.update(post_params)
		redirect_to post_path(post)
	end

	def create
		@post = current_user.posts.new(post_params)
		if @post.save
			flash[:success]="新しく投稿されました"
		    redirect_to root_path
		    else
			redirect_to new_post_path , alert: '投稿内容に不備があります'
	    end
	end

	def show
		@post = Post.find(params[:id])
		@user = @post.user
		@comment = PostComment.new
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path
	end

	 private
	  def post_params
	    params.require(:post).permit(:dish_image, :user_image, :menu_title, :price, :comment, :shop_name, :adress)
	  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def top
  end

  def search
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def show
  	@user = User.find(params[:id])
  	@posts = @user.posts
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: '会員情報の更新が完了しました。'
    else
      render :edit
    end
  end

  def index
    @users = User.all
  end

  def about
  end

  def destroy
	  @user = User.find(params[:id])
	  @user.destroy
	  redirect_to root_path
  end

private
	def user_params
		params.require(:user).permit(:name, :user_image, :introduction, :prefecture, :genres)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ramen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1"><!-- レスポンシブができなかったので追記-->
  </head>

  <body>


      <header>
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to 'Ramen-Hunters', root_path, class: "navbar-brand" %>
            </div>
            
            <div class="collapse navbar-collapse" id="navbarEexample">
              <ul class="nav navbar-nav">
                <% if user_signed_in? %>
                  <li><%= link_to '探す', top_path %></li>
                  <li><%= link_to '新規投稿', new_post_path %></li>
                  <li><%= link_to 'マイページ', user_path(current_user) %></li>
                  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to 'about', about_path %></li>
                  <li><%= link_to '探す', top_path %></li>
                  <li><%= link_to 'ログイン', new_user_session_path %></li>
                  <li><%= link_to '新規登録', new_user_registration_path %></li>
                  <li><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>

      </header>
      <!div style="background-color: #FF8856;">

    <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>投稿編集ページ</h1>


<div class="flex">
	<%= form_with model: @post, url: post_path(@post), local: true, method: :patch do |f| %>
	<div>
		<%= f.file_field :dish_image, class: 'img_field', style: 'display:none;' %>
		<%= attachment_image_tag @post, :dish_image, format: "jpeg", fallback: "no-image.png", size:'200x200', onClick: "$('.img_field').click()", class: 'img-thumbnail img-responsive img_prev' %>
	<p>選択するとプレビューされます。<br>画像未選択のままだと、<br>「No Image」になります。</p>
	</div>
	<table>
		<thead>
			<tr>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= f.label :menu_title, "メニュー" %></td>
				<td><%= f.text_field :menu_title %></td>
			</tr>
			<tr>
				<td><%= f.label :price, "価格" %></td>
				<td><%= f.text_field :price %>円</td>
			</tr>
				<td><%= f.label :shop_name, "店舗名" %></td>
				<td><%= f.text_field :shop_name %></td>
			</tr>
				<td><%= f.label :adress, "店舗住所" %></td>
				<td><%= f.text_field :adress %></td>
			</tr>
			<tr>
				<td><%= f.label :comment, "コメント" %></td>
				<td><%= f.text_area :comment %></td>
			</tr>
		</tbody>
	</table>
	<div class="flex align-center pl5">
		<%= f.submit "更新する", class: "btn btn-primary" %>
	</div>
</div>
<% end %>

app/views/posts/index.html.erb
<div class="container">

	<% if flash[:notice] %>
	  <p><%= flash[:notice] %></p>
	<% end %>

<h1 align="center">投稿一覧</h1>

  <div id="posts-container">
    <div class="col-lg-3">
    </div>


      <div class="col-lg-6">
	      <div class="post-tl proported-box box-square">
				<% @posts.each do |post| %>
				  <div class="inner">
			        <%= link_to post_path(post) do %>
			          <div class="index-dish">
			          	<%= attachment_image_tag post ,:dish_image,:fill, 200, 200,  format: "jpeg", fallback: "no-image.png", class: 'img_prev '%>

			            <div class="avatar">
				          <%= attachment_image_tag post.user , :user_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img img_prev" , fallback: "no-image.png" %>
				        </div>
			            <div class="post-info">
							  <span>
							  	<%= post.shop_name %><br>
							    <%= post.adress %>
							  </span>
					    </div>
			          </div>
			        <% end %>
			      </div>
			    <% end %>
			<% if flash[:success] %>
				<p><%= flash[:success] %></p>
			<% end %>
		  </div>
	  </div>
	<div class="col-lg-3">
    </div>

  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="col-lg-3">
    </div>
    <div class="col-lg-6">
      <h1>本日のハントしたラーメン</h1>
		  <%= form_for(@post, url: posts_path) do |f| %>
		    <div class="row">
				<div class="col-lg-6">
					<%= f.file_field :dish_image, class: 'img_field', style: 'display:none;' %>
					<%= attachment_image_tag @post, :dish_image, format: "jpeg", fallback: "no-image.png", size:'200x200', onClick: "$('.img_field').click()", class: 'img-thumbnail img-responsive img_prev' %>
				<p>選択するとプレビューされます。<br>画像未選択のままだと、<br>「No Image」になります。</p>
				</div>
				<div class="col-lg-6">
				<table>
					<thead>
						<tr>
							<th></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><%= f.label :menu_title, "メニュー" %></td>
							<td><%= f.text_field :menu_title %></td>
						</tr>
						<tr>
							<td><%= f.label :price, "価格" %></td>
							<td><%= f.text_field :price %>円</td>
						</tr>
							<td><%= f.label :shop_name, "店舗名" %></td>
							<td><%= f.text_field :shop_name %></td>
						</tr>
							<td><%= f.label :adress, "店舗住所" %></td>
							<td><%= f.text_field :adress %></td>
						</tr>
						<tr>
							<td><%= f.label :comment, "コメント" %></td>
							<td><%= f.text_area :comment %></td>
						</tr>
					</tbody>
				</table>
				</div>
				<div class="flex align-center pl5">
					<%= f.submit "投稿する", class: "btn btn-primary" %>
				</div>
					<% if flash[:alert] %>
					  <p><%= flash[:alert] %></p>
					<% end %>
		    </div>
		 <% end %>
	</div>
	<div class="col-lg-3">
    </div>
</div>

app/views/posts/show.html.erb
<div class="container">

    <div class="col-lg-2">
    </div>


    <div class="col-lg-8">
      <table class="row">
      	<h1>投稿詳細ページ</h1>
      	<div class="col-lg-6">
			<%= link_to user_path(@user) do %>
			  <%= attachment_image_tag @user , :user_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img img_prev" , fallback: "no-image.png" %>
			<% end %>
			<%= attachment_image_tag @post ,:dish_image, format: "jpeg", fallback: "no-image.png" %><br>
				<% if user_signed_in? %>
					<% if current_user.already_liked?(@post) %>
					  <%= link_to post_favorites_path(@post), method: :delete do %>
						  <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
						  <%= @post.favorites.count %> いいね
					  <% end %>
					<% else %>
					  <%= link_to post_favorites_path(@post), method: :post do %>
						  <i class="fa fa-heart-o" aria-hidden="true"></i>
						  <%= @post.favorites.count %> いいね
					  <% end %>
					<% end %>
				<% end %>
	    </div>

        <div class="col-lg-6">
				<tbody>
					<tr>
					  <th>メニュー名</th>
					  <td><%= @post.menu_title %></td>
					</tr>
					<tr>
					  <th>価格</th>
					  <td><%= @post.price %>円</td>
					</tr>
					<tr>
					  <th>店舗名</th>
					  <td><%= @post.shop_name %></td>
					</tr>
					<tr>
					  <th>所在地</th>
					  <td><%= @post.adress %></td>
					</tr>
					<tr>
					  <th>コメント</th>
					  <td><%= @post.comment %></td>
					</tr>



					<tr>
						<th></th>
						<td></td>
						<% if @post.user == current_user %>
						<%= link_to "編集する", edit_post_path(@post), class: "btn-sm btn-success edit_post_#{@post.id}" %>
						<%= link_to "削除する", post_path(@post), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_post_#{@post.id}" %>
						<% end %>
						</td>
					</tr>
			   </tbody>
		</div>
    </table>

				  <tr>
					<th>【みんなのコメント】</th>
					<td><% @post.post_comments.each do |post_comment| %>
							<div>
							  <%= link_to post_comment.user.name, user_path(post_comment.user_id) %>さん
							</div>
							<div>
								<%= post_comment.comment %>
							</div>

							<% if post_comment.user == current_user %>
							  	 <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete, class: "btn btn-danger pull-right" %>
							<% end %>
						<% end %>
					</td>
				  </tr>

					<%= form_for [@post, @comment] do |f| %>
						<div>
							<%= f.text_area :comment, size: "15x5", class: "form-control"%>
						</div>
						<%= f.submit "コメントを投稿する", class: "btn btn-lg btn-base-1 mt-20" %>
					<% end %>
					<% if flash[:alert] %>
					  <p><%= flash[:alert] %></p>
					<% end %>
	</div>


    <div class="col-lg-2">
    </div>

</div>

app/views/searches/search.html.erb
<h1>Searches#search</h1>
<p>Find me in app/views/searches/search.html.erb</p>

app/views/searches/top.html.erb
<div class="container">
  <div class="col-lg-3">
  </div>

    <div class="col-lg-6">
    	<div class="row search">
    		<div class="col-lg-2">
    		</div>
			<div class="col-lg-3">
				<%= link_to "ユーザーを探す", users_path, class: "btn btn-success btn-lg blank " %>
			</div>
    		<div class="col-lg-2">
    		</div>
			<div class="col-lg-3">
				<%= link_to "店舗を探す", root_path, class: "btn btn-success btn-lg blank " %><br>
				※工事中です
			</div>
			<div class="col-lg-2">
    		</div>
	    </div>
  </div>

  <div class="col-lg-3">
  </div>

</div>

app/views/users/about.html.erb
<div class="container">

    <div class="col-lg-3">
    </div>

    <div class="col-lg-6">

		<h1>What's ラーメンハンターズ？</h1>

		<div class= "margin : 50px">
		ラーメン食べたとき、友達は美味しいと絶賛していても、自分には普通だなと思ったことはありませんか？<br>
		どんなに絶品のラーメンでも人によって好みが分かれるもの。<br>
		ただ、やっはりみんな大好きなラーメン。<br>
		あなたも、自分と好みが合いそうな人からラーメンを探してみませんか？<br>
		</div>
		<div class="about">
			<%= image_tag asset_path('about1.jpg') %>
		</div>
	</div>

    <div class="col-lg-3">
    </div>

</div>

app/views/users/account.html.erb
<h1>Users#account</h1>
<p>Find me in app/views/users/account.html.erb</p>

app/views/users/edit.html.erb
<div class="container">
	<div class="col-lg-3">
    </div>

    <div class="col-lg-6">
		<h1>登録情報変更</h1>

		<%= form_for(@user) do |f| %>
		  <%= f.file_field :user_image, class: 'img_field', style: 'display:none;' %>
		  <%= attachment_image_tag @user, :user_image, :fill, 100, 100, format: 'jpeg', onClick: "$('.img_field').click()", class: "img-circle pull-left profile-img img_prev" , fallback: "no-image.png" %>

		  <table>
		    <thead>
				<tr>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><%= f.label :ユーザーネーム %> </td>
					<td><%= f.text_field :name, :placeholder =>"#{@user.name}" %></td>
				</tr>
				<tr>
					<td><%= f.label :お住まいの都道府県 %> </td>
					<td><%= f.select :prefecture, User.prefectures.keys, :placeholder =>"#{@user.prefecture}" %></td>
				</tr>
				<tr>
					<td><%= f.label :好みのジャンル %> </td>
					<td><%= f.select :genres,User.genres.keys, :placeholder =>"#{@user.prefecture}" %></td>
				</tr>
				<tr>
					<td><%= f.label :紹介文 %> </td>
					<td><%= f.text_area :introduction, class: 'form-control', :placeholder =>"#{@user.introduction}" %></td>
				</tr>
				<tr>
					<td><%= f.submit "編集内容を保存する", class: "btn btn-primary" %></td>
					<td><%= link_to "退会する", user_path, class: "btn btn-danger", method: :delete %></td>
				</tr>
		    </tbody>
		  </table>

		<% end %>
	</div>

	<div class="col-lg-3">
    </div>

</div>>

app/views/users/index.html.erb
<div class="container">

    <div class="col-lg-1">
    </div>

	<div class="col-lg-10">
		<h1>ユーザー一覧</h1>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>ユーザー画像</th>
					<th>ユーザーネーム</th>
                    <th>住まいの地域</th>
                    <th>好きなジャンル</th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<th><%= link_to user_path(user) do %>
						  <%= attachment_image_tag(user, :user_image, :fill, 100, 100, fallback: "no-image.png",size:'100x100') %>
					    <% end %>
					</th>
				    <td><%= user.name %></td>
                    <td><%= user.prefecture %></td>
                    <td><%= user.genres %></td>
				</tr>
				<% end %>
			</tbody>
	    </table>

    <div class="col-lg-1">
    </div>

</div>

app/views/users/show.html.erb
<div class="container">

    <div class="col-lg-3">
    </div>

    <div class="col-lg-6">
	<h1>ユーザー詳細</h1>

		<table class="row">
		  <div class="col-lg-6">
		  <%= attachment_image_tag @user , :user_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img img_prev" , fallback: "no-image.png" %>
		  </div>
		  <div class="col-lg-6">
			<thead>
				<tr>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>ユーザーネーム</td>
					<td><%= @user.name %></td>
				</tr>
				<tr>
					<td>好みのジャンル</td>
					<td><%= @user.genres %></td>
				</tr>
				<tr>
					<td>住まいの地域</td>
					<td><%= @user.prefecture %></td>
				</tr>
				<tr>
					<td>紹介文</td>
					<td><%= @user.introduction %></td>
				</tr>
				<% if @user == current_user %>
				<div>
					<%= link_to "登録情報変更", edit_user_path(@user.id), class: "btn btn-success" %>
				</div>
				<% end %>
			</tbody>
		  </div>
		</table>

	    <div class="row">
		<% @posts.each do |post| %>
			<div class="inner">
			  <%= link_to post_path(post) do %>
			    <div class="index-dish">
			    <%= attachment_image_tag post ,:dish_image, format: "jpeg", fallback: "no-image.png", class: 'img_prev' %>
			    </div>
	            <div class="post-info">
				  <span>
				  	<%= post.shop_name %><br>
				    <%= post.adress %>
				  </span>
			    </div>
			  <% end %>
			</div>
		<% end %>
	    </div>
	</div>
    <div class="col-lg-3">
    </div>
</div>